### PR TITLE
 Fix css when displaying groups

### PR DESCRIPTION
**Pull request by Cyboulette**
Typo issue, the style tag was closed before color.

**Before fix:**
```html
<span class="assigned-group" style="background-color: #000000" color:"#ff3fe4">MyGroup</span>
```
**With fix:**
```html
<span class="assigned-group" style="background-color: #000000; color:#ff3fe4;">MyGroup</span>
```

### CODE REVIEW

**Comment by Cyboulette** [comment]
(Sorry about number of commits but I have edited all files from github.com website directyl)

**Comment by creecros** [comment]
i do the same thing:
image

curious though, `color:#ff3fe4;"`. That should only be `"black"` or `"white"`, where is that coming from?

**Comment by Cyboulette** [comment]
> i do the same thing:
> image
> 
> curious though, `color:#ff3fe4;"`. That should only be `"black"` or `"white"`, where is that coming from?

Ahah, it's for the example only :) Yes is black or white in fact.

Thank's for the merge :)

**Comment by creecros** [comment]
that was my suspicion, as I was pretty sure `background-color: 000000` would never happen either. 😛

**Pull request merged**
